name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action-issue:
    name: Test Action (Issue)
    uses: ./.github/workflows/test-action.yml
    with:
      issue-number: 3

  test-action-pr:
    if: github.event_name == 'pull_request'
    name: Test Action (PR)
    uses: ./.github/workflows/test-action.yml
    with:
      issue-number: ${{ github.event.pull_request.number }}
